import { NextResponse } from "next/server";
import { Buffer } from "buffer";

export const runtime = "nodejs";

export async function POST(req: Request) {
  try {
    const token = process.env.GITHUB_TOKEN;
    const owner = process.env.GITHUB_REPO_OWNER;
    const repo = process.env.GITHUB_REPO_NAME;

    if (!token || !owner || !repo) {
      return NextResponse.json(
        { error: "Missing GitHub env vars (GITHUB_TOKEN, GITHUB_REPO_OWNER, GITHUB_REPO_NAME)" },
        { status: 500 }
      );
    }

    const body = await req.json().catch(() => ({}));
    const prTitle = String(body?.title ?? "AI Generated Feature");
    const content = String(body?.content ?? "");

    if (!content.trim()) {
      return NextResponse.json({ error: "Missing content" }, { status: 400 });
    }

    const ghHeaders = {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
      "User-Agent": "opspilot-ai-feature-builder",
    };

    // 1) Get repo to find default branch
    const repoRes = await fetch(`https://api.github.com/repos/${owner}/${repo}`, {
      headers: ghHeaders,
    });

    const repoText = await repoRes.text();
    if (!repoRes.ok) {
      return NextResponse.json(
        { error: `GitHub repo lookup failed: ${repoRes.status} ${repoText}` },
        { status: 500 }
      );
    }

    const repoData = JSON.parse(repoText);
    const baseBranch = repoData.default_branch;

    // 2) Get base branch SHA
    const refRes = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/git/ref/heads/${baseBranch}`,
      { headers: ghHeaders }
    );

    const refText = await refRes.text();
    if (!refRes.ok) {
      return NextResponse.json(
        { error: `GitHub ref lookup failed: ${refRes.status} ${refText}` },
        { status: 500 }
      );
    }

    const refData = JSON.parse(refText);
    const baseSha = refData.object.sha;

    // 3) Create new branch
    const branchName = `ai-feature-${Date.now()}`;

    const createRefRes = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/git/refs`,
      {
        method: "POST",
        headers: ghHeaders,
        body: JSON.stringify({
          ref: `refs/heads/${branchName}`,
          sha: baseSha,
        }),
      }
    );

    const createRefText = await createRefRes.text();
    if (!createRefRes.ok) {
      return NextResponse.json(
        { error: `GitHub create branch failed: ${createRefRes.status} ${createRefText}` },
        { status: 500 }
      );
    }

    // 4) Create file on new branch
    const filePath = `ai-output/${branchName}.md`;

    const putFileRes = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`,
      {
        method: "PUT",
        headers: ghHeaders,
        body: JSON.stringify({
          message: "AI generated feature artifacts",
          content: Buffer.from(content, "utf8").toString("base64"),
          branch: branchName,
        }),
      }
    );

    const putFileText = await putFileRes.text();
    if (!putFileRes.ok) {
      return NextResponse.json(
        { error: `GitHub put file failed: ${putFileRes.status} ${putFileText}` },
        { status: 500 }
      );
    }

    // 5) Open PR
    const prRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
      method: "POST",
      headers: ghHeaders,
      body: JSON.stringify({
        title: prTitle,
        head: branchName,
        base: baseBranch,
        body: "Automated PR generated by AI Feature Builder.",
      }),
    });

    const prText = await prRes.text();
    if (!prRes.ok) {
      return NextResponse.json(
        { error: `GitHub create PR failed: ${prRes.status} ${prText}` },
        { status: 500 }
      );
    }

    const prData = JSON.parse(prText);

    return NextResponse.json({ pr_url: prData.html_url, branch: branchName, filePath });
 } catch (e: unknown) {
  const msg = e instanceof Error ? e.message : String(e);
  return new Response(JSON.stringify({ error: msg }), {
    status: 500,
    headers: { "Content-Type": "application/json" },
  });
}
}
